matrix:
  fast_finish: true
  include:
    - language: go
      go: 1.11.x
      go_import_path: github.com/whtiehack/996.ICU

      install:
        - echo "install
        
      script:
        - echo "script list"
        - go run ./blacklist/archive

      after_script:
        - sleep 1

      after_success:
        - echo "after_success"
        - sleep 1


git:
  depth: 10


